apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: r6ruk0x64-python 
  janus-idp.io/tekton: r6ruk0x64-python
  backstage.io/kubernetes-id: r6ruk0x64-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: r6ruk0x64-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml