apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: r6ruk0x64-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: r6ruk0x64-python 
  name: r6ruk0x64-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: r6ruk0x64-python 
